spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddip?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  properties:
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${smtp-username}
    password: ${smtp-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


jwt:
  key: rTPmA9Sgk+Q1XwuJbG7E6xFFUhQpdi+al5iyPnRTK/Q=
